# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5574ae738f46e4e15d2b937dc1b633fe39cf9dff6b7e542c7b0bba0c037d3eddf828e0e197f120435906c1eb2b5a199dabb7ae1fb341a6fa813f2931738ca6

test:
  secret_key_base: 5c8adf81fc3b19920a4c9158f71499de9cc301b2e003339168da622aec2a0b99257dbb0c8d20f7dc457c119eabf01b49d52d68f72fd400d52e77b10f97a02421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
